services:
  - type: web
    name: anotherInstanceOfTheWebSite
    runtime: node
    plan: free
    region: frankfurt
    repo: https://github.com/RivalSid/serverlessTest.git
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fuckOffDB
          property: connectionString
databases:
  - name: fuckOffDB
    plan: free
    region: frankfurt
